### ISSUE TITLE
down drop should drop down a level on scaffolding

### ISSUE THREAD

**Issue by sbrother** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#12]

**Comment by sbrother** [comment]
90% fixed (thanks Kerby!) just need to modify code so this only happens when there is actually a level below player.

**Comment by KerbySmith** [comment]
can no longer drop from a level lower than 150. this seems to be a good height as far as my limited testing goes. It allows you to drop if there is not a level underneath you but only from the higher platforms. it allows for the player to drop from an upper level with no lower level preemptively in order to land on a lower level that is scrolling to them which plays pretty well.
